// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ex1.proto

#ifndef PROTOBUF_INCLUDED_ex1_2eproto
#define PROTOBUF_INCLUDED_ex1_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ex1_2eproto 

namespace protobuf_ex1_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ex1_2eproto
namespace E477Ex1 {
class annotated_point;
class annotated_pointDefaultTypeInternal;
extern annotated_pointDefaultTypeInternal _annotated_point_default_instance_;
}  // namespace E477Ex1
namespace google {
namespace protobuf {
template<> ::E477Ex1::annotated_point* Arena::CreateMaybeMessage<::E477Ex1::annotated_point>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace E477Ex1 {

// ===================================================================

class annotated_point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:E477Ex1.annotated_point) */ {
 public:
  annotated_point();
  virtual ~annotated_point();

  annotated_point(const annotated_point& from);

  inline annotated_point& operator=(const annotated_point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  annotated_point(annotated_point&& from) noexcept
    : annotated_point() {
    *this = ::std::move(from);
  }

  inline annotated_point& operator=(annotated_point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const annotated_point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const annotated_point* internal_default_instance() {
    return reinterpret_cast<const annotated_point*>(
               &_annotated_point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(annotated_point* other);
  friend void swap(annotated_point& a, annotated_point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline annotated_point* New() const final {
    return CreateMaybeMessage<annotated_point>(NULL);
  }

  annotated_point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<annotated_point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const annotated_point& from);
  void MergeFrom(const annotated_point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(annotated_point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string label = 3;
  void clear_label();
  static const int kLabelFieldNumber = 3;
  const ::std::string& label() const;
  void set_label(const ::std::string& value);
  #if LANG_CXX11
  void set_label(::std::string&& value);
  #endif
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  ::std::string* mutable_label();
  ::std::string* release_label();
  void set_allocated_label(::std::string* label);

  // int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:E477Ex1.annotated_point)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr label_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ex1_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// annotated_point

// int32 x = 1;
inline void annotated_point::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 annotated_point::x() const {
  // @@protoc_insertion_point(field_get:E477Ex1.annotated_point.x)
  return x_;
}
inline void annotated_point::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:E477Ex1.annotated_point.x)
}

// int32 y = 2;
inline void annotated_point::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 annotated_point::y() const {
  // @@protoc_insertion_point(field_get:E477Ex1.annotated_point.y)
  return y_;
}
inline void annotated_point::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:E477Ex1.annotated_point.y)
}

// string label = 3;
inline void annotated_point::clear_label() {
  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& annotated_point::label() const {
  // @@protoc_insertion_point(field_get:E477Ex1.annotated_point.label)
  return label_.GetNoArena();
}
inline void annotated_point::set_label(const ::std::string& value) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:E477Ex1.annotated_point.label)
}
#if LANG_CXX11
inline void annotated_point::set_label(::std::string&& value) {
  
  label_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:E477Ex1.annotated_point.label)
}
#endif
inline void annotated_point::set_label(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:E477Ex1.annotated_point.label)
}
inline void annotated_point::set_label(const char* value, size_t size) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:E477Ex1.annotated_point.label)
}
inline ::std::string* annotated_point::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:E477Ex1.annotated_point.label)
  return label_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* annotated_point::release_label() {
  // @@protoc_insertion_point(field_release:E477Ex1.annotated_point.label)
  
  return label_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void annotated_point::set_allocated_label(::std::string* label) {
  if (label != NULL) {
    
  } else {
    
  }
  label_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:E477Ex1.annotated_point.label)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace E477Ex1

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ex1_2eproto
